#cloud-config
# Cloud config for application servers

runcmd:
  # Install docker
  - curl -sSL https://get.docker.com/ | sudo sh
  # Pull the image
  - sudo docker pull joostrovers/mcma-ec2-transform-service > /var/log/docker-install.log
  # Run docker
  - sudo docker run -d -e SERVICES_URL=${services_url} -e SERVICES_AUTH_TYPE=${services_auth_type} -e SERVICES_AUTH_CONTEXT=${services_auth_context} -p 80:8080 joostrovers/mcma-ec2-transform-service > /var/log/docker-run.log